// osmanHerreraSiteReact/src/components/footer.tsx
import { useForm } from 'react-hook-form';
import { useContactForm } from '../hooks/useContactForm';
import '../App.css';

interface ContactFormData {
  nombre: string;
  correoElectronico: string;
  content: string;
}

export const Footer = () => {
  const { isSending, sendEmail } = useContactForm();

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isValid },
  } = useForm<ContactFormData>({
    mode: 'onChange',
  });

  const onSubmit = async (data: ContactFormData) => {
    const success = await sendEmail(data);
    if (success) reset();
  };

  return (
    <div className="w-full">
      <form
        className={`form-glass transition-all ${
          isSending ? 'blur-state' : ''
        }`}
        onSubmit={handleSubmit(onSubmit)}
      >
        {/* Nombre */}
        <div className="form-group">
          <label htmlFor="nombre" className="form-label">
            Nombre / Empresa
          </label>
          <input
            id="nombre"
            type="text"
            className="form-input"
            placeholder="Tu nombre o empresa"
            {...register('nombre', {
              required: 'El nombre es obligatorio',
            })}
          />
          {errors.nombre && (
            <span className="form-error">{errors.nombre.message}</span>
          )}
        </div>

        {/* Email */}
        <div className="form-group">
          <label htmlFor="correoElectronico" className="form-label">
            Correo Electrónico
          </label>
          <input
            id="correoElectronico"
            type="email"
            className="form-input"
            placeholder="tu@email.com"
            {...register('correoElectronico', {
              required: 'El correo es obligatorio',
              pattern: {
                value: /^\S+@\S+$/i,
                message: 'El formato de correo no es válido',
              },
            })}
          />
          {errors.correoElectronico && (
            <span className="form-error">
              {errors.correoElectronico.message}
            </span>
          )}
        </div>

        {/* Mensaje */}
        <div className="form-group">
          <label htmlFor="content" className="form-label">
            Mensaje
          </label>
          <textarea
            id="content"
            className="form-textarea"
            placeholder="Tu mensaje aquí..."
            {...register('content', {
              required: 'El mensaje es obligatorio',
              minLength: {
                value: 10,
                message: 'El mensaje debe tener al menos 10 caracteres',
              },
            })}
          />
          {errors.content && (
            <span className="form-error">{errors.content.message}</span>
          )}
        </div>

        {/* Validación Info */}
        {!isValid && (
          <p className="form-error mb-4">
            ℹ️ Completa correctamente todos los campos
          </p>
        )}

        {/* Submit Button */}
        <button
          type="submit"
          disabled={!isValid || isSending}
          className="form-button w-full mb-3"
        >
          {isSending ? (
            <span className="inline-flex items-center gap-2">
              <span className="inline-block w-4 h-4 border-2 border-transparent border-t-2 rounded-full animate-spin"></span>
              Enviando...
            </span>
          ) : (
            'Enviar Mensaje'
          )}
        </button>

        <p className="text-xs opacity-70 text-center">
          Responderé lo antes posible
        </p>
      </form>
    </div>
  );
};

// osmanHerreraSite/src/app/shared/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { finalize } from 'rxjs/operators';
import { EmailService } from '../../services/email.service';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styles: ``
})
export class FooterComponent implements OnInit {

  public contactForm!: FormGroup;
  public isSending: boolean = false;

  constructor(private fb: FormBuilder, private emailService: EmailService) { }

  ngOnInit(): void {
    this.contactForm = this.fb.group({
      nombre: ['', [Validators.required]],
      correoElectronico: ['', [
        Validators.required,
        Validators.pattern(/^\S+@\S+$/i)
      ]],
      content: ['', [
        Validators.required,
        Validators.minLength(10)
      ]]
    });
  }

  // Get para facilitar el acceso a los controles en el HTML
  get f() {
    return this.contactForm.controls;
  }

  enviarFormularioContacto() {
    // Doble seguridad: si es inválido o ya se está enviando, no hace nada
    if (this.contactForm.invalid || this.isSending) return;

    this.isSending = true;

    this.emailService.enviarCorreo(this.contactForm.value)
      .pipe(
        finalize(() => {
          this.isSending = false;
        })
      )
      .subscribe({
        next: () => {
          alert("Mensaje enviado con éxito");
          this.contactForm.reset();
        },
        error: (err) => {
          console.error('Error en el envío:', err);
          alert("No se pudo enviar el mensaje");
        }
      });
  }
}

<div class="w-full">
  <form
    [formGroup]="contactForm"
    (ngSubmit)="enviarFormularioContacto()"
    class="form-glass transition-all"
    [class.blur-state]="isSending"
  >
    <div class="form-group">
      <label for="nombre" class="form-label">Nombre / Empresa</label>
      <input
        id="nombre"
        type="text"
        formControlName="nombre"
        class="form-input"
        placeholder="Tu nombre o empresa"
      />
      <span *ngIf="f['nombre'].touched && f['nombre'].errors?.['required']" class="form-error">
        El nombre es obligatorio
      </span>
    </div>

    <div class="form-group">
      <label for="correoElectronico" class="form-label">Correo Electrónico</label>
      <input
        id="correoElectronico"
        type="email"
        formControlName="correoElectronico"
        class="form-input"
        placeholder="tu@email.com"
      />
      <div *ngIf="f['correoElectronico'].touched && f['correoElectronico'].errors">
        <span *ngIf="f['correoElectronico'].errors['required']" class="form-error">
          El correo es obligatorio
        </span>
        <span *ngIf="f['correoElectronico'].errors['pattern']" class="form-error">
          El formato de correo no es válido
        </span>
      </div>
    </div>

    <div class="form-group">
      <label for="content" class="form-label">Mensaje</label>
      <textarea
        id="content"
        formControlName="content"
        class="form-textarea"
        placeholder="Tu mensaje aquí..."
      ></textarea>
      <div *ngIf="f['content'].touched && f['content'].errors">
        <span *ngIf="f['content'].errors['required']" class="form-error">
          El mensaje es obligatorio
        </span>
        <span *ngIf="f['content'].errors['minlength']" class="form-error">
          El mensaje debe tener al menos 10 caracteres
        </span>
      </div>
    </div>

    <p *ngIf="contactForm.invalid && contactForm.touched" class="form-error mb-4">
      ℹ️ Completa correctamente todos los campos
    </p>

    <button
      type="submit"
      [disabled]="contactForm.invalid || isSending"
      class="form-button w-full mb-3"
    >
      <span *ngIf="isSending; else defaultText" class="inline-flex items-center gap-2">
        <span class="inline-block w-4 h-4 border-2 border-transparent border-t-white rounded-full animate-spin"></span>
        Enviando...
      </span>
      <ng-template #defaultText>Enviar Mensaje</ng-template>
    </button>

    <p class="text-xs opacity-70 text-center">
      Responderé lo antes posible
    </p>
  </form>
</div>
