// osmanHerreraSite/src/app/app.component.ts
import { Component, OnInit, HostBinding, HostListener } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  // Binding para el color dinámico del scroll
  @HostBinding('style.--variant') variantColor = '#ff5e00';

  public socialIcons = [
    { title: 'linkedin', icon: '/assets/icons/social1.svg', address: 'https://www.linkedin.com/in/osmanherrera/' },
    { title: 'whatsapp', icon: '/assets/icons/social2.svg', address: 'https://wa.me/50489709082' },
    { title: 'email', icon: '/assets/icons/social3.svg', address: 'mailto:contact@osmanherrera.dev' },
    { title: 'github', icon: '/assets/icons/social4.svg', address: 'https://github.com/osmanjosue' },
  ];

  public certificates = [
  {
    platform: 'Udemy',
    title: 'Master en JavaScript: Aprender JS, jQuery, Angular, NodeJS',
    month: 'Enero',
    date: 2024,
    link: 'https://www.udemy.com/certificate/UC-53ecf1b8-00d0-49a5-a948-ae2e6d2ecfd0/',
  },
  {
    platform: 'Udemy',
    title: 'Angular Avanzado: Lleva tus bases al siguiente nivel - MEAN',
    month: 'Agosto',
    date: 2023,
    link: 'https://www.udemy.com/certificate/UC-03475c4f-f50b-491c-a1e2-4975b8aab381/',
  },
  {
    platform: 'Devtalles',
    title: 'GIT+GitHub: Todo un sistema de control de versiones de cero',
    month: 'Abril',
    date: 2024,
    link: 'https://cursos.devtalles.com/certificates/zl0noyjvkn',
  },
  {
    platform: 'Udemy',
    title: 'Alojamiento de sitio web en modo serverless en Amazon AWS',
    month: 'Julio',
    date: 2022,
    link: 'https://www.udemy.com/certificate/UC-4840328a-96c0-47c9-afa4-04f65c37096d/',
  },
];

  public technologies: any[] = [];
  private techNames = ['CSS', 'HTML', 'JavaScript', 'TypeScript', 'Angular', 'NodeJS', 'GitHub', 'Git', 'MongoDB', 'Photoshop', 'Illustrator', 'JWT', 'Python', 'n8n', 'Docker'];

  ngOnInit() {
    this.technologies = this.techNames.map(name => ({
      title: name,
      icon: `/assets/icons/technologies-${name}.svg`
    }));
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    const offset = window.scrollY;
    const maxScroll = document.documentElement.scrollHeight - window.innerHeight;
    const percentage = offset / maxScroll;

    // Lógica simple de cambio de color (Naranja a Morado)
    if (percentage > 0.5) {
      this.variantColor = '#663399'; // RebecaPurple
    } else {
      this.variantColor = '#ff5e00'; // Naranja
    }
  }
}

<div class="w-full">
  <header class="header-sticky">
    <div class="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
      <div class="flex items-center gap-3">
        <i class="OHicono w-10 h-10"></i>
        <h1 class="text-2xl font-bold">
          <span class="color-variant">Osman</span>Herrera.dev
        </h1>
      </div>

      <nav class="hidden md:flex gap-8">
        <a
          href="#hero"
          class="text-sm font-semibold hover:color-variant transition"
          >Inicio</a
        >
        <a
          href="#technologies"
          class="text-sm font-semibold hover:color-variant transition"
          >Habilidades</a
        >
        <a
          href="#formation"
          class="text-sm font-semibold hover:color-variant transition"
          >Formación</a
        >
        <a
          href="#experience"
          class="text-sm font-semibold hover:color-variant transition"
          >Experiencia</a
        >
        <a
          href="#contact"
          class="text-sm font-semibold hover:color-variant transition"
          >Contacto</a
        >
      </nav>
    </div>
  </header>

  <!-- ================= HERO SECTION ================= -->
  <section
    id="hero"
    class="min-h-[80vh] flex items-center justify-center pt-20"
  >
    <div class="text-center px-4 max-w-4xl">
      <h2 class="text-5xl md:text-7xl font-bold mb-6">
        Desarrollo web con <span class="color-variant">lógica</span> y
        <span class="color-variant">pasión</span>.
      </h2>
      <p class="text-xl opacity-80 mb-8">
        FullStack Developer | Graphic Designer | Constant Learner
      </p>
      <a href="#contact" class="cv-button px-8 py-3 text-lg"
        >Hablemos de tu proyecto</a
      >
    </div>
  </section>

  <section class="w-full py-20 px-4 bg-black">
    <div class="max-w-4xl mx-auto">
      <div class="profile-card">
        <div class="profile-image">
          <img
            src="/assets/images/IMG_20230209_080358.jpg"
            alt="Osman Herrera"
          />
        </div>

        <div class="profile-info">
          <h2 class="profile-name">Osman Herrera</h2>

          <div class="profile-badges">
            <span class="badge">Desarrollador FullStack</span>
            <span class="badge">Diseñador Gráfico</span>
          </div>

          <div class="social-buttons">
            <a
              *ngFor="let icon of socialIcons"
              [href]="icon.address"
              target="_blank"
              class="social-btn"
              [title]="icon.title"
            >
              <span
                class="icon-mask"
                [style.--icon-url]="'url(' + icon.icon + ')'"
              ></span>
            </a>
          </div>

          <a
            href="https://raw.githubusercontent.com/osmanjosue/pdfCv/d3122180d29d9b5bf0b7acca4c33b7af8264304e/CV_oherrera_dev_eng_2026.pdf"
            target="_blank"
            class="cv-button mb-6 inline-flex"
          >
            <span
              class="icon-mask w-6 h-6 mr-2"
              [style.--icon-url]="'url(/assets/icons/Download_icon.svg)'"
            ></span>
            Descargar CV
          </a>

          <div class="text-base leading-relaxed opacity-90 max-w-2xl mx-auto">
            <p>
              ¡Hola! Soy
              <span class="color-variant font-semibold"
                >desarrollador web independiente</span
              >
              y me considero un
              <span class="color-variant font-semibold"> eterno aprendiz</span>.
              Más allá de dominar una herramienta específica, mi verdadera
              fortaleza es una lógica de programación sólida y la capacidad de
              aprender lo que sea necesario para hacer realidad tu proyecto.
            </p>
            <p class="mt-4">
              Me mantengo siempre actualizado para ofrecerte
              <span class="color-variant font-semibold"
                >soluciones ágiles, funcionales y modernas</span
              >.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="technologies" class="technologies-section">
    <div class="max-w-6xl mx-auto">
      <div class="section-header">
        <h2 class="section-title">Habilidades Técnicas</h2>
        <p class="section-subtitle">Tecnologías y herramientas que domino</p>
      </div>
      <div class="technologies-grid">
        <div *ngFor="let tech of technologies" class="tech-card">
          <span
            class="tech-icon icon-mask"
            [style.--icon-url]="'url(' + tech.icon + ')'"
          ></span>
          <p class="tech-name">{{ tech.title }}</p>
        </div>
      </div>
    </div>
  </section>

  <section id="formation" class="formation-section">
    <div class="max-w-4xl mx-auto">
      <div class="section-header mb-12">
        <h2 class="section-title">Formación</h2>
        <p class="section-subtitle">Educación y Certificaciones</p>
      </div>
      <div class="certificates-container">
        <div class="certificate-card">
          <div class="certificate-platform">UNIVERSIDAD</div>
          <h3 class="certificate-title">
            Técnico Universitario en Desarrollo de Aplicaciones Computacionales
          </h3>
          <p class="certificate-date">UTH • Estudiando Actualmente</p>
        </div>
        <div *ngFor="let cert of certificates" class="certificate-card">
          <div class="certificate-platform">{{ cert.platform }}</div>
          <h3 class="certificate-title">{{ cert.title }}</h3>
          <p class="certificate-date">{{ cert.month }} {{ cert.date }}</p>
          <a [href]="cert.link" target="_blank" class="certificate-link"
            >Ver Certificado →</a
          >
        </div>
      </div>
    </div>
  </section>

  <section id="experience" class="experience-section">
    <div class="max-w-5xl mx-auto">
      <div class="section-header mb-12">
        <h2 class="section-title">Experiencia Profesional</h2>
        <p class="section-subtitle">Proyectos y roles que he desempeñado</p>
      </div>
      <div class="experience-container">
        <div class="experience-card">
          <div class="experience-header">
            <div>
              <h3 class="experience-title">
                Desarrollador <span class="color-variant">web</span>
              </h3>
              <p class="text-lg opacity-70">Fundación Prolancho</p>
            </div>
            <span class="experience-date">2023 - 2026</span>
          </div>
          <p class="experience-description">
            Desarrollo del sitio web con Angular 15 en frontend y NodeJS para
            API backend. Base de datos MongoDB con Cloudinary para gestión de
            imágenes. Autenticación con JWT y validación de credenciales para
            panel administrativo. Alojado en AWS EC2 con Ubuntu, NGINX y PM2.
          </p>
          <div class="experience-tech">
            <span class="tech-badge">Angular 15</span>
            <span class="tech-badge">NodeJS</span>
            <span class="tech-badge">MongoDB</span>
            <span class="tech-badge">JWT</span>
            <span class="tech-badge">AWS EC2</span>
            <span class="tech-badge">NGINX</span>
          </div>
          <div class="mt-6 flex gap-4">
            <a
              href="https://github.com/osmanjosue/fundacionProlanchoSiteFrontAndBack"
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center gap-2 text-sm font-semibold color-variant hover:opacity-80"
            >
              <span
                class="icon-mask w-4 h-4"
                [style.--icon-url]="
                  'url(/assets/icons/technologies-GitHub.svg)'
                "
              ></span>
              Repositorio
            </a>
            <a
              href="https://www.fundacionprolancho.org"
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center gap-2 text-sm font-semibold color-variant hover:opacity-80"
            >
              <span
                class="icon-mask w-4 h-4"
                [style.--icon-url]="'url(/assets/icons/website.svg)'"
              ></span>
              Sitio Web
            </a>
          </div>
        </div>

        <div class="experience-card">
          <div class="experience-header">
            <div>
              <h3 class="experience-title">
                Diseñador <span class="color-variant">Gráfico</span> &
                Coordinador de Productos
              </h3>
              <p class="text-lg opacity-70">Empresa de Diseño y Estampado</p>
            </div>
            <span class="experience-date">2012 - 2023</span>
          </div>

          <p class="experience-description">
            Diseño y creación de ilustraciones profesionales. Separación de
            colores para serigrafía y sublimación. Coordinación de personal,
            cumplimiento de objetivos de producción, y lanzamiento de nuevos
            productos con fechas puntuales basados en metas establecidas.
          </p>

          <div class="experience-tech">
            <span class="tech-badge">Diseño Gráfico</span>
            <span class="tech-badge">Photoshop</span>
            <span class="tech-badge">Ilustrator</span>
            <span class="tech-badge">Gestión de Equipos</span>
            <span class="tech-badge">Serigrafía</span>
            <span class="tech-badge">Sublimación</span>
          </div>

          <div class="mt-6">
            <a
              href="https://www.facebook.com/beomegusta/"
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center gap-2 text-sm font-semibold color-variant hover:opacity-80"
            >
              <span
                class="icon-mask w-4 h-4"
                [style.--icon-url]="'url(/assets/icons/facebook.svg)'"
              ></span>
              Página de Facebook
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="contact" class="contact-section py-20">
    <div class="max-w-4xl mx-auto px-4">
      <h2 class="section-title mb-12 text-center">Contacto</h2>
      <div class="contact-container grid md:grid-cols-2 gap-12 items-start">
        <div class="contact-info flex flex-col gap-6">
          <a
            *ngFor="let icon of socialIcons"
            [href]="icon.address"
            class="contact-method"
          >
            <span
              class="contact-icon icon-mask"
              [style.--icon-url]="'url(' + icon.icon + ')'"
            ></span>
            <span class="contact-text">{{ icon.title }}</span>
          </a>
        </div>
        <app-footer></app-footer>
      </div>
    </div>
  </section>

  <footer class="footer py-12 border-t border-white/10 text-center opacity-60 text-sm">
    <div class="footer-content">
      <p class="footer-credit">
        © 2026 Osman Herrera. Todos los derechos reservados.
      </p>
      <p class="footer-credit">
        Diseñado y desarrollado con ❤️ por Osman Herrera
      </p>
    </div>
  </footer>
</div>

// osmanHerreraSiteReact/src/App.tsx
import React, { useMemo } from 'react';
import './App.css';
import { Footer } from './components/footer';

// ===========================================================================
// 1. INTERFACES Y DATOS (Fuera de App para evitar redeclaraciones)
// ===========================================================================

interface Certificate {
  platform: string;
  title: string;
  month: string;
  date: number;
  link: string;
}

interface SocialIcon {
  title: string;
  icon: string;
  address: string;
}

interface Technology {
  title: string;
  icon: string;
}

const CERTIFICATES: Certificate[] = [
  {
    platform: 'Udemy',
    title: 'Master en JavaScript: Aprender JS, jQuery, Angular, NodeJS',
    month: 'Enero',
    date: 2024,
    link: 'https://www.udemy.com/certificate/UC-53ecf1b8-00d0-49a5-a948-ae2e6d2ecfd0/',
  },
  {
    platform: 'Udemy',
    title: 'Angular Avanzado: Lleva tus bases al siguiente nivel - MEAN',
    month: 'Agosto',
    date: 2023,
    link: 'https://www.udemy.com/certificate/UC-03475c4f-f50b-491c-a1e2-4975b8aab381/',
  },
  {
    platform: 'Devtalles',
    title: 'GIT+GitHub: Todo un sistema de control de versiones de cero',
    month: 'Abril',
    date: 2024,
    link: 'https://cursos.devtalles.com/certificates/zl0noyjvkn',
  },
  {
    platform: 'Udemy',
    title: 'Alojamiento de sitio web en modo serverless en Amazon AWS',
    month: 'Julio',
    date: 2022,
    link: 'https://www.udemy.com/certificate/UC-4840328a-96c0-47c9-afa4-04f65c37096d/',
  },
];

const SOCIAL_ICONS: SocialIcon[] = [
  { title: 'linkedin', icon: '/assets/icons/social1.svg', address: 'https://www.linkedin.com/in/osmanherrera/' },
  { title: 'whatsapp', icon: '/assets/icons/social2.svg', address: 'https://wa.me/50489709082' },
  { title: 'email', icon: '/assets/icons/social3.svg', address: 'mailto:contact@osmanherrera.dev' },
  { title: 'github', icon: '/assets/icons/social4.svg', address: 'https://github.com/osmanjosue' },
];

const TECH_NAMES: string[] = [
  'CSS', 'HTML', 'JavaScript', 'TypeScript', 'Angular', 'NodeJS', 'GitHub', 
  'Git', 'MongoDB', 'Photoshop', 'Illustrator', 'JWT', 'Python', 'n8n', 'Docker'
];


// ===========================================================================
// 2. COMPONENTE APP
// ===========================================================================

const App: React.FC = () => {
  // --- LÓGICA DE TRANSFORMACIÓN (USEMEMO) ---
  const technologies = useMemo<Technology[]>(() => {
    return TECH_NAMES.map((name) => ({
      title: name,
      icon: `/assets/icons/technologies-${name}.svg`,
    }));
  }, []);

  return (
    <div className="w-full">
      {/* ================= STICKY HEADER ================= */}
      <header className="header-sticky">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          {/* Logo & Brand */}
          <div className="flex items-center gap-3">
            <i className="OHicono w-10 h-10"></i>
            <h1 className="text-2xl font-bold">
              <span className="color-variant">Osman</span>Herrera.dev
            </h1>
          </div>

          {/* Navigation */}
          <nav className="hidden md:flex gap-8">
            <a href="#hero" className="text-sm font-semibold hover:color-variant transition">
              Inicio
            </a>
            <a href="#technologies" className="text-sm font-semibold hover:color-variant transition">
              Habilidades
            </a>
            <a href="#formation" className="text-sm font-semibold hover:color-variant transition">
              Formación
            </a>
            <a href="#experience" className="text-sm font-semibold hover:color-variant transition">
              Experiencia
            </a>
            <a href="#contact" className="text-sm font-semibold hover:color-variant transition">
              Contacto
            </a>
          </nav>
        </div>
      </header>

      {/* ================= HERO SECTION ================= */}
      

      {/* ================= PROFILE SECTION ================= */}
      <section className="w-full py-20 px-4 bg-black">
        <div className="max-w-4xl mx-auto">
          <div className="profile-card">
            {/* Profile Image */}
            <div className="profile-image">
              <img
                src="/assets/images/IMG_20230209_080358.jpg"
                alt="Osman Herrera"
              />
            </div>

            {/* Profile Info */}
            <div className="profile-info">
              <h2 className="profile-name">Osman Herrera</h2>

              {/* Badges */}
              <div className="profile-badges">
                <span className="badge">Desarrollador FullStack</span>
                <span className="badge">Diseñador Gráfico</span>
                <span className="badge">Eterno Aprendiz</span>
              </div>

              {/* Social Buttons */}
              <div className="social-buttons">
                {SOCIAL_ICONS.map((icon, i) => (
                  <a
                    key={i}
                    href={icon.address}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="social-btn"
                    title={icon.title}
                  >
                    <span
                      className="icon-mask"
                      style={
                        {
                          '--icon-url': `url(${icon.icon})`,
                        } as React.CSSProperties
                      }
                    ></span>
                  </a>
                ))}
              </div>

              {/* CV Button */}
              <a
                href="https://raw.githubusercontent.com/osmanjosue/pdfCv/d3122180d29d9b5bf0b7acca4c33b7af8264304e/CV_oherrera_dev_eng_2026.pdf"
                target="_blank"
                rel="noopener noreferrer"
                className="cv-button mb-6 inline-flex"
              >
                <span
                  className="icon-mask w-6 h-6 mr-2"
                  style={
                    {
                      '--icon-url': 'url("/assets/icons/Download_icon.svg")',
                    } as React.CSSProperties
                  }
                ></span>
                Descargar CV
              </a>

              {/* About Me */}
              <div className="text-base leading-relaxed opacity-90 max-w-2xl mx-auto">
                <p>
                  ¡Hola! Soy <span className="color-variant font-semibold">desarrollador web independiente</span> y me considero un
                  <span className="color-variant font-semibold"> eterno aprendiz</span>. Más allá de dominar una herramienta específica,
                  mi verdadera fortaleza es una lógica de programación sólida y la
                  capacidad de aprender lo que sea necesario para hacer realidad
                  tu proyecto.
                </p>
                <p className="mt-4">
                  Me mantengo siempre actualizado para ofrecerte
                  <span className="color-variant font-semibold"> soluciones ágiles, funcionales y modernas</span>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ================= TECHNOLOGIES SECTION ================= */}
      <section id="technologies" className="technologies-section">
        <div className="max-w-6xl mx-auto">
          <div className="section-header">
            <h2 className="section-title">Habilidades Técnicas</h2>
            <p className="section-subtitle">
              Tecnologías y herramientas que domino
            </p>
          </div>

          <div className="technologies-grid">
            {technologies.map((tech, i) => (
              <div key={i} className="tech-card">
                <span
                  className="tech-icon icon-mask"
                  style={
                    { '--icon-url': `url(${tech.icon})` } as React.CSSProperties
                  }
                ></span>
                <p className="tech-name">{tech.title}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ================= FORMATION SECTION ================= */}
      <section id="formation" className="formation-section">
        <div className="max-w-4xl mx-auto">
          <div className="section-header mb-12">
            <h2 className="section-title">Formación</h2>
            <p className="section-subtitle">Educación y Certificaciones</p>
          </div>

          <div className="certificates-container">
            {/* Universidad */}
            <div className="certificate-card">
              <div className="certificate-platform">UNIVERSIDAD</div>
              <h3 className="certificate-title">
                Técnico Universitario en Desarrollo de Aplicaciones Computacionales
              </h3>
              <p className="certificate-date">Universidad Tecnológica de Honduras • Estudiando Actualmente</p>
            </div>

            {/* Certificados */}
            {CERTIFICATES.map((cert, i) => (
              <div key={i} className="certificate-card">
                <div className="certificate-platform">{cert.platform}</div>
                <h3 className="certificate-title">{cert.title}</h3>
                <p className="certificate-date">
                  {cert.month} {cert.date}
                </p>
                <a
                  href={cert.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="certificate-link"
                >
                  Ver Certificado →
                </a>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ================= EXPERIENCE SECTION ================= */}
      <section id="experience" className="experience-section">
        <div className="max-w-5xl mx-auto">
          <div className="section-header mb-12">
            <h2 className="section-title">Experiencia Profesional</h2>
            <p className="section-subtitle">Proyectos y roles que he desempeñado</p>
          </div>

          <div className="experience-container">
            {/* Experience Card 1 */}
            <div className="experience-card">
              <div className="experience-header">
                <div>
                  <h3 className="experience-title">
                    Desarrollador <span className="color-variant">web</span>
                  </h3>
                  <p className="text-lg opacity-70">Fundación Prolancho</p>
                </div>
                <span className="experience-date">2023 - 2026</span>
              </div>

              <p className="experience-description">
                Desarrollo del sitio web con Angular 15 en frontend y NodeJS para API backend.
                Base de datos MongoDB con Cloudinary para gestión de imágenes. Autenticación con JWT
                y validación de credenciales para panel administrativo. Alojado en AWS EC2 con Ubuntu,
                NGINX y PM2.
              </p>

              <div className="experience-tech">
                <span className="tech-badge">Angular 15</span>
                <span className="tech-badge">NodeJS</span>
                <span className="tech-badge">MongoDB</span>
                <span className="tech-badge">JWT</span>
                <span className="tech-badge">AWS EC2</span>
                <span className="tech-badge">NGINX</span>
              </div>

              <div className="mt-6 flex gap-4">
                <a
                  href="https://github.com/osmanjosue/fundacionProlanchoSiteFrontAndBack"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm font-semibold color-variant hover:opacity-80"
                >
                  <span
                    className="icon-mask w-4 h-4"
                    style={
                      {
                        '--icon-url':
                          'url(/assets/icons/technologies-GitHub.svg)',
                      } as React.CSSProperties
                    }
                  ></span>
                  Repositorio
                </a>
                <a
                  href="https://www.fundacionprolancho.org"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm font-semibold color-variant hover:opacity-80"
                >
                  <span
                    className="icon-mask w-4 h-4"
                    style={
                      {
                        '--icon-url': 'url(/assets/icons/website.svg)',
                      } as React.CSSProperties
                    }
                  ></span>
                  Sitio Web
                </a>
              </div>
            </div>

            {/* Experience Card 2 */}
            <div className="experience-card">
              <div className="experience-header">
                <div>
                  <h3 className="experience-title">
                    Diseñador <span className="color-variant">Gráfico</span> & Coordinador de Productos
                  </h3>
                  <p className="text-lg opacity-70">Empresa de Diseño y Estampado</p>
                </div>
                <span className="experience-date">2012 - 2023</span>
              </div>

              <p className="experience-description">
                Diseño y creación de ilustraciones profesionales. Separación de colores para serigrafía
                y sublimación. Coordinación de personal, cumplimiento de objetivos de producción,
                y lanzamiento de nuevos productos con fechas puntuales basados en metas establecidas.
              </p>

              <div className="experience-tech">
                <span className="tech-badge">Diseño Gráfico</span>
                <span className="tech-badge">Photoshop</span>
                <span className="tech-badge">Ilustrator</span>
                <span className="tech-badge">Gestión de Equipos</span>
                <span className="tech-badge">Serigrafía</span>
                <span className="tech-badge">Sublimación</span>
              </div>

              <div className="mt-6">
                <a
                  href="https://www.facebook.com/beomegusta/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm font-semibold color-variant hover:opacity-80"
                >
                  <span
                    className="icon-mask w-4 h-4"
                    style={
                      {
                        '--icon-url': 'url(/assets/icons/facebook.svg)',
                      } as React.CSSProperties
                    }
                  ></span>
                  Página de Facebook
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ================= CONTACT SECTION ================= */}
      <section id="contact" className="contact-section">
        <div className="max-w-4xl mx-auto">
          <div className="section-header mb-12">
            <h2 className="section-title">Ponte en Contacto</h2>
            <p className="section-subtitle">
              Varias formas de conectar conmigo
            </p>
          </div>

          <div className="contact-container">
            {/* Contact Methods */}
            <div className="contact-info">
              <h3 className="contact-title mb-8">Contacta Conmigo</h3>
              <div className="contact-methods">
                {SOCIAL_ICONS.map((icon, i) => (
                  <a
                    key={i}
                    href={icon.address}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="contact-method"
                  >
                    <span
                      className="contact-icon icon-mask"
                      style={
                        {
                          '--icon-url': `url(${icon.icon})`,
                        } as React.CSSProperties
                      }
                    ></span>
                    <span className="contact-text">{icon.title}</span>
                  </a>
                ))}
              </div>
            </div>

            {/* Contact Form */}
            <Footer />
          </div>
        </div>
      </section>

      {/* ================= FOOTER ================= */}
      <footer className="footer">
        <div className="footer-content">
          <p className="footer-credit">
            © 2026 Osman Herrera. Todos los derechos reservados.
          </p>
          <p className="footer-credit">
            Diseñado y desarrollado con ❤️ por Osman Herrera
          </p>
        </div>
      </footer>
    </div>
  );


};

export default App;
