// osmanHerreraSite/src/app/shared/rich-text/rich-text.component.ts
import { Component, Input } from '@angular/core';
import { RichText, RichTextSegment } from '@shared/content';

// Renderiza un RichText del config compartido (texto + segmentos con formato)
@Component({
  selector: 'app-rich-text',
  template: `<ng-container *ngFor="let seg of value"
    ><ng-container *ngIf="asSegment(seg) as s; else plain"
      ><a *ngIf="s.href; else span" [href]="s.href" [ngClass]="classes(s)">{{ s.text }}</a
      ><ng-template #span><span [ngClass]="classes(s)">{{ s.text }}</span></ng-template></ng-container
    ><ng-template #plain>{{ seg }}</ng-template></ng-container
  >`,
})
export class RichTextComponent {
  @Input({ required: true }) value: RichText = [];

  asSegment(seg: string | RichTextSegment): RichTextSegment | null {
    return typeof seg === 'string' ? null : seg;
  }

  classes(s: RichTextSegment): Record<string, boolean> {
    return {
      'color-variant': !!s.highlight,
      'font-semibold': !!s.bold,
      'underline hover:opacity-85': !!s.href,
    };
  }
}

// osmanHerreraSiteReact/src/components/RichText.tsx
import React from 'react';
import type { RichText as RichTextValue } from '@shared/content';

// Renderiza un RichText del config compartido (texto + segmentos con formato)
export const RichText: React.FC<{ value: RichTextValue }> = ({ value }) => (
  <>
    {value.map((segment, i) => {
      if (typeof segment === 'string') return <React.Fragment key={i}>{segment}</React.Fragment>;

      const className = [
        segment.highlight && 'color-variant',
        segment.bold && 'font-semibold',
        segment.href && 'underline hover:opacity-85',
      ]
        .filter(Boolean)
        .join(' ');

      return segment.href ? (
        <a key={i} href={segment.href} className={className}>
          {segment.text}
        </a>
      ) : (
        <span key={i} className={className}>
          {segment.text}
        </span>
      );
    })}
  </>
);
